import { Theme } from './theme.types';

export const theme: Theme = {
  color: {
    component: {
      bottomMenuBackground: '#FFFFFF',
      bottomMenuText: '#0a0a0a',
      ordinalSelectedBorder: '#2b34c0',
      ordinalTypeJson: '#89d2e6',
      ordinalTypePlainText: '#89d2e6',
      ordinalTypeUnsupported: '#0a0a0a',
      pageLoaderSpinner: '#2b34c0',
      pageLoaderSpinnerBorder: '#0a0a0a50',
      pageLoaderText: '#0a0a0a',
      primaryButtonLeftGradient: '#2b34c0',
      primaryButtonRightGradient: '#89d2e6',
      primaryButtonText: '#FFFFFF',
      progressBar: '#89d2e6',
      progressBarTrack: '#F5F5F5',
      queueBannerSynced: '#89d2e6',
      queueBannerSyncedText: '#0a0a0a',
      queueBannerSyncing: '#2b34c0',
      queueBannerSyncingText: '#FFFFFF',
      secondaryOutlineButtonGradientLeft: '#2b34c0',
      secondaryOutlineButtonGradientRight: '#89d2e6',
      secondaryOutlineButtonText: '#FFFFFF',
      snackbarError: '#FF4646',
      snackbarErrorText: '#FFFFFF',
      snackbarSuccess: '#89d2e6',
      snackbarSuccessText: '#0a0a0a',
      snackbarWarning: '#2b34c0',
      snackbarWarningText: '#FFFFFF',
      tabSelectedLeftGradient: '#2b34c0',
      tabSelectedRightGradient: '#89d2e6',
      tabSelectedText: '#FFFFFF',
      tabUnselected: '#EAF8FD',
      tabUnselectedText: '#0a0a0a',
      toggleSwitchOn: '#2b34c0',
      warningButton: '#FF4646',
      warningButtonText: '#0a0a0a',
    },
    global: {
      neutral: '#FFFFFF',
      gray: '#98A2B3',
      row: '#F5F5F5',
      walletBackground: '#FFFFFF',
      contrast: '#0a0a0a',
    },
  },
  settings: {
    repo: 'https://github.com/bitcoin-sv/spv-wallet-browser',
    services: {
      apps: false,
      bsv20: true,
      locks: true,
      ordinals: true,
    },
    walletName: 'SPV Wallet',
  },
};
